# Generated by Django 5.0.3 on 2024-03-10 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('no_of_tickets', models.CharField(max_length=200)),
                ('event_image', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='aval_date')),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('email', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('per_hour_charge', models.IntegerField()),
                ('aval_date', models.DateTimeField(verbose_name='aval_date')),
                ('Image', models.CharField(max_length=200)),
                ('certificate', models.BooleanField()),
                ('oter_skills_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePostByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience', models.IntegerField()),
                ('available_date', models.DateTimeField()),
                ('open_to_work', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('service_img', models.ImageField(blank=True, upload_to='img/')),
                ('per_hour_rate', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
