version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt  # Install project dependencies
      - pip install pylint  # Install pylint for static code analysis

  pre_build:
    commands:
      - python --version  # Print Python version for verification
      - pylint --disable=all --enable=error $CODEBUILD_SRC_DIR/*.py  # Run pylint with only error messages
      - pylint --disable=all --enable=error $CODEBUILD_SRC_DIR/servicesApp/*.py  # Run pylint with only error messages

artifacts:
  files:
    - '**/*'  # Include all files in the artifact
