version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint
      # Check if Sonar Scanner is installed, if not, download and install it
      - if [ ! -x "$(command -v sonar-scanner)" ]; then
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip &&
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip &&
          export PATH=$PATH:./sonar-scanner-cli-4.6.2.2472-linux/bin/;
        fi

  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/manage.py || true

  build:
    commands:
      - |
        if [ -z "$Project" ]; then
            echo "Error: SonarCloud project key not found."
            exit 1
        fi
        if [ -z "$Organization" ]; then
            echo "Error: SonarCloud organization key not found."
            exit 1
        fi
        if [ -z "$HOST" ]; then
            echo "Error: SonarCloud host URL not found."
            exit 1
        fi
        if [ -z "$LOGIN" ]; then
            echo "Error: SonarCloud login token not found."
            exit 1
        fi

        sonar-scanner \
            -Dsonar.projectKey="$Project" \
            -Dsonar.organization="$Organization" \
            -Dsonar.host.url="$HOST" \
            -Dsonar.login="$LOGIN" \
            -X
