version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint
      # Check if Sonar Scanner is installed, if not, download and install it
      - if [ ! -x "$(command -v sonar-scanner)" ]; then
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip &&
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip &&
          export PATH=$PATH:./sonar-scanner-cli-4.6.2.2472-linux/bin/;
        fi

  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/manage.py || true

  build:
    commands:
      - sonar-scanner \
          -Dsonar.projectKey="azharakhter555" \
          -Dsonar.organization="azharakhter555" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login="dfb96a75ff67413791f60ca1b049976beccfaec6" \
          -X

artifacts:
  files:
    - '**/*'
